<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <SelfContained>true</SelfContained>
    <IsAotCompatible>true</IsAotCompatible>
    <InvariantGlobalization>true</InvariantGlobalization>
    <NoWarn>$(NoWarn);IL2067;IL2091;IL2104</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Confluent.Kafka" Version="2.14.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KafkaConsumerLab.Contracts\KafkaConsumerLab.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootDescriptor Include="..\KafkaConsumerLab.Aot.ConfluentKafkaRoots.xml" />
  </ItemGroup>
</Project>
